services:

    Symfony\Component\Security\Core\User\UserProviderInterface: '@fos_user.user_provider.username'

    jira_auth.user_provider:
        class: AppBundle\Repository\JiraUserProvider

    AppBundle\Repository\JiraUserProviderInterface: "@jira_auth.user_provider"
